# game settings
TILESIZE = 25
WIDTH = 19 * TILESIZE
HEIGHT = 17 * TILESIZE
GRIDWIDTH = WIDTH / TILESIZE
GRIDHEIGHT = HEIGHT / TILESIZE

FPS = 24

DARKGREY = (40, 40, 40)
YELLOW = (255, 255, 0)
LIGHTGREY = (100, 100, 100)
BGCOLOR = DARKGREY

PLAYERSPRITE = "images/player.png"
PLAYERXML = "images/player.xml"
WATERSPRITE = "images/water.png"
WATERXML = "images/water.xml"
KEYSPRITE = "images/key.png"
KEYXML = "images/key.xml"

BLUE = (30, 45, 255)


DYING = 1
RESETTING = 16

TREASURELEVEL = 3
KEYLEVEL = 9
MOVINGBLOCKLEVEL = 12
